# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(429, 384)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/wind_icon.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QWidget#Form {\n"
"    background-color: rgb(202, 219, 255);\n"
"    border-radius: 15px;\n"
"    \n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(10, -1, 10, 6)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 2, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 0, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setMinimumSize(QtCore.QSize(400, 350))
        self.tabWidget.setMaximumSize(QtCore.QSize(400, 350))
        self.tabWidget.setStyleSheet("QTabWidget::pane { /* The tab widget frame */\n"
"    border-radius: 15px\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 35px; /* move to the right by 5px */\n"
"}\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    background-color: rgb(86, 137, 230);\n"
"    min-width: 55px;\n"
"    min-height: 20px;\n"
"    padding: 2px;\n"
"    font:7pt \"Verdana\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    background-color: rgb(51, 84, 176);\n"
"    margin-top: 5px; /* make non-selected tabs look smaller */\n"
"}")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.data_tab = QtWidgets.QWidget()
        self.data_tab.setObjectName("data_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.data_tab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.All_inputs = QtWidgets.QWidget(self.data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.All_inputs.sizePolicy().hasHeightForWidth())
        self.All_inputs.setSizePolicy(sizePolicy)
        self.All_inputs.setMinimumSize(QtCore.QSize(0, 0))
        self.All_inputs.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px")
        self.All_inputs.setObjectName("All_inputs")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.All_inputs)
        self.verticalLayout_3.setContentsMargins(30, 20, 30, 20)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.dataF_btn = QtWidgets.QPushButton(self.All_inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataF_btn.sizePolicy().hasHeightForWidth())
        self.dataF_btn.setSizePolicy(sizePolicy)
        self.dataF_btn.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.dataF_btn.setFont(font)
        self.dataF_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 113, 176);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    font: 7pt \"Verdana\";\n"
"    border-style:none;\n"
"\n"
"    padding:3px;\n"
"    min-height:15px;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(87, 150, 204);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(46, 101, 156);\n"
"}")
        self.dataF_btn.setFlat(False)
        self.dataF_btn.setObjectName("dataF_btn")
        self.gridLayout.addWidget(self.dataF_btn, 0, 0, 1, 1)
        self.saveDir_line = QtWidgets.QLineEdit(self.All_inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveDir_line.sizePolicy().hasHeightForWidth())
        self.saveDir_line.setSizePolicy(sizePolicy)
        self.saveDir_line.setMinimumSize(QtCore.QSize(0, 21))
        self.saveDir_line.setMaximumSize(QtCore.QSize(16777215, 21))
        self.saveDir_line.setStyleSheet("font:7pt \"Verdana\";\n"
"border: 0.5px solid rgb(196, 196, 196);\n"
"border-radius: 5px")
        self.saveDir_line.setReadOnly(True)
        self.saveDir_line.setObjectName("saveDir_line")
        self.gridLayout.addWidget(self.saveDir_line, 2, 1, 1, 1)
        self.dataF_line = QtWidgets.QLineEdit(self.All_inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataF_line.sizePolicy().hasHeightForWidth())
        self.dataF_line.setSizePolicy(sizePolicy)
        self.dataF_line.setMinimumSize(QtCore.QSize(0, 21))
        self.dataF_line.setMaximumSize(QtCore.QSize(16777215, 21))
        self.dataF_line.setStyleSheet("font:7pt \"Verdana\";\n"
"border: 0.5px solid rgb(196, 196, 196);\n"
"border-radius: 5px")
        self.dataF_line.setReadOnly(True)
        self.dataF_line.setObjectName("dataF_line")
        self.gridLayout.addWidget(self.dataF_line, 0, 1, 1, 1)
        self.timeF_btn = QtWidgets.QPushButton(self.All_inputs)
        self.timeF_btn.setMinimumSize(QtCore.QSize(150, 21))
        self.timeF_btn.setMaximumSize(QtCore.QSize(16777215, 21))
        self.timeF_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 113, 176);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    font:7pt \"Verdana\";\n"
"    border-style:none;\n"
"\n"
"    padding:3px;\n"
"    min-height:15px;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(87, 150, 204);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(46, 101, 156);\n"
"}")
        self.timeF_btn.setFlat(False)
        self.timeF_btn.setObjectName("timeF_btn")
        self.gridLayout.addWidget(self.timeF_btn, 1, 0, 1, 1)
        self.timeF_line = QtWidgets.QLineEdit(self.All_inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeF_line.sizePolicy().hasHeightForWidth())
        self.timeF_line.setSizePolicy(sizePolicy)
        self.timeF_line.setMinimumSize(QtCore.QSize(0, 21))
        self.timeF_line.setMaximumSize(QtCore.QSize(16777215, 21))
        self.timeF_line.setStyleSheet("font:7pt \"Verdana\";\n"
"border: 0.5px solid rgb(196, 196, 196);\n"
"border-radius: 5px")
        self.timeF_line.setReadOnly(True)
        self.timeF_line.setObjectName("timeF_line")
        self.gridLayout.addWidget(self.timeF_line, 1, 1, 1, 1)
        self.saveDir_btn = QtWidgets.QPushButton(self.All_inputs)
        self.saveDir_btn.setMaximumSize(QtCore.QSize(16777215, 21))
        self.saveDir_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 113, 176);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    font:7pt \"Verdana\";\n"
"    border-style:none;\n"
"\n"
"    padding:3px;\n"
"    min-height:15px;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(87, 150, 204);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(46, 101, 156);\n"
"}")
        self.saveDir_btn.setFlat(False)
        self.saveDir_btn.setObjectName("saveDir_btn")
        self.gridLayout.addWidget(self.saveDir_btn, 2, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.widget_4 = QtWidgets.QWidget(self.All_inputs)
        self.widget_4.setToolTip("")
        self.widget_4.setToolTipDuration(15000)
        self.widget_4.setStyleSheet("\n"
"QWidget#Label {\n"
"    font:7pt \"Verdana\";\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setStyleSheet("font:7pt \"Verdana\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.data_ver_rbtn = QtWidgets.QRadioButton(self.widget_4)
        self.data_ver_rbtn.setToolTip("")
        self.data_ver_rbtn.setStyleSheet("font:7pt \"Verdana\";")
        self.data_ver_rbtn.setChecked(True)
        self.data_ver_rbtn.setObjectName("data_ver_rbtn")
        self.horizontalLayout_4.addWidget(self.data_ver_rbtn)
        self.data_hor_rbtn = QtWidgets.QRadioButton(self.widget_4)
        self.data_hor_rbtn.setStyleSheet("font:7pt \"Verdana\";")
        self.data_hor_rbtn.setObjectName("data_hor_rbtn")
        self.horizontalLayout_4.addWidget(self.data_hor_rbtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.widget = QtWidgets.QWidget(self.All_inputs)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("font:7pt \"Verdana\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.title_line = QtWidgets.QLineEdit(self.widget)
        self.title_line.setMinimumSize(QtCore.QSize(0, 20))
        self.title_line.setStyleSheet("QLineEdit {\n"
"    font:7pt \"Verdana\";\n"
"    border: 0.5px solid rgb(196, 196, 196);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-color:rgb(146, 209, 244);\n"
"}\n"
"")
        self.title_line.setObjectName("title_line")
        self.horizontalLayout.addWidget(self.title_line)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.All_inputs)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setStyleSheet("font:7pt \"Verdana\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignLeft)
        self.utime_line = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.utime_line.sizePolicy().hasHeightForWidth())
        self.utime_line.setSizePolicy(sizePolicy)
        self.utime_line.setMinimumSize(QtCore.QSize(20, 20))
        self.utime_line.setStyleSheet("QLineEdit {\n"
"    font:7pt \"Verdana\";\n"
"    border: 0.5px solid rgb(196, 196, 196);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-color:rgb(146, 209, 244);\n"
"}\n"
"")
        self.utime_line.setObjectName("utime_line")
        self.horizontalLayout_3.addWidget(self.utime_line, 0, QtCore.Qt.AlignLeft)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setStyleSheet("font:7pt \"Verdana\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.uaxis_line = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uaxis_line.sizePolicy().hasHeightForWidth())
        self.uaxis_line.setSizePolicy(sizePolicy)
        self.uaxis_line.setMinimumSize(QtCore.QSize(40, 20))
        self.uaxis_line.setStyleSheet("QLineEdit {\n"
"    font:7pt \"Verdana\";\n"
"    border: 0.5px solid rgb(196, 196, 196);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-color:rgb(146, 209, 244);\n"
"}\n"
"")
        self.uaxis_line.setObjectName("uaxis_line")
        self.horizontalLayout_3.addWidget(self.uaxis_line)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.All_inputs)
        self.label_5.setStyleSheet("font:7pt \"Verdana\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.save_v_box = QtWidgets.QCheckBox(self.All_inputs)
        self.save_v_box.setStyleSheet("font:7pt \"Verdana\";")
        self.save_v_box.setChecked(True)
        self.save_v_box.setTristate(False)
        self.save_v_box.setObjectName("save_v_box")
        self.horizontalLayout_5.addWidget(self.save_v_box)
        self.save_i_box = QtWidgets.QCheckBox(self.All_inputs)
        self.save_i_box.setEnabled(True)
        self.save_i_box.setToolTip("")
        self.save_i_box.setStyleSheet("font:7pt \"Verdana\";")
        self.save_i_box.setChecked(False)
        self.save_i_box.setObjectName("save_i_box")
        self.horizontalLayout_5.addWidget(self.save_i_box)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.OK_btn = QtWidgets.QPushButton(self.All_inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OK_btn.sizePolicy().hasHeightForWidth())
        self.OK_btn.setSizePolicy(sizePolicy)
        self.OK_btn.setMinimumSize(QtCore.QSize(50, 25))
        self.OK_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 113, 176);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    font:7pt \"Verdana\";\n"
"    border-style:none;\n"
"\n"
"    padding:5px;\n"
"    min-height:15px;\n"
"    min-width: 40px;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(87, 150, 204);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(46, 101, 156);\n"
"}")
        self.OK_btn.setObjectName("OK_btn")
        self.verticalLayout_3.addWidget(self.OK_btn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.All_inputs)
        self.tabWidget.addTab(self.data_tab, "")
        self.func_tab = QtWidgets.QWidget()
        self.func_tab.setObjectName("func_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.func_tab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.func_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_5.setContentsMargins(30, 20, 30, 21)
        self.gridLayout_5.setVerticalSpacing(15)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setHorizontalSpacing(4)
        self.gridLayout_3.setVerticalSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_23 = QtWidgets.QLabel(self.widget_2)
        self.label_23.setStyleSheet("font: 6pt \"Verdana\";")
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.widget_2)
        self.label_22.setStyleSheet("font:7pt \"Verdana\";")
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 0, 0, 1, 1)
        self.func_i_2 = QtWidgets.QLineEdit(self.widget_2)
        self.func_i_2.setStyleSheet("QLineEdit {\n"
"    font:7pt \"Verdana\";\n"
"    border: 0.5px solid rgb(196, 196, 196);\n"
"    border-radius: 5px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-color:rgb(146, 209, 244);\n"
"}\n"
"")
        self.func_i_2.setObjectName("func_i_2")
        self.gridLayout_3.addWidget(self.func_i_2, 0, 1, 1, 1)
        self.function_info = QtWidgets.QPushButton(self.widget_2)
        self.function_info.setMinimumSize(QtCore.QSize(20, 21))
        self.function_info.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 113, 176);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    font:7pt \"Verdana\";\n"
"    border-style:none;\n"
"\n"
"    padding:3px;\n"
"    min-height:15px;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(87, 150, 204);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(46, 101, 156);\n"
"}")
        self.function_info.setObjectName("function_info")
        self.gridLayout_3.addWidget(self.function_info, 0, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.widget_2)
        self.label_15.setStyleSheet("font:7pt \"Verdana\";")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.tnum_i_2 = QtWidgets.QLineEdit(self.widget_2)
        self.tnum_i_2.setStyleSheet("QLineEdit {\n"
"    font:7pt \"Verdana\";\n"
"    border: 0.5px solid rgb(196, 196, 196);\n"
"    border-radius: 5px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-color:rgb(146, 209, 244);\n"
"}\n"
"")
        self.tnum_i_2.setObjectName("tnum_i_2")
        self.horizontalLayout_8.addWidget(self.tnum_i_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.gridLayout_5.addLayout(self.horizontalLayout_8, 4, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem9, 5, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setHorizontalSpacing(8)
        self.gridLayout_6.setVerticalSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ymax_i_2 = QtWidgets.QLineEdit(self.widget_2)
        self.ymax_i_2.setStyleSheet("QLineEdit {\n"
"    font:7pt \"Verdana\";\n"
"    border: 0.5px solid rgb(196, 196, 196);\n"
"    border-radius: 5px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-color:rgb(146, 209, 244);\n"
"}\n"
"")
        self.ymax_i_2.setObjectName("ymax_i_2")
        self.gridLayout_6.addWidget(self.ymax_i_2, 1, 4, 1, 1)
        self.xmax_i_2 = QtWidgets.QLineEdit(self.widget_2)
        self.xmax_i_2.setStyleSheet("QLineEdit {\n"
"    font:7pt \"Verdana\";\n"
"    border: 0.5px solid rgb(196, 196, 196);\n"
"    border-radius: 5px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-color:rgb(146, 209, 244);\n"
"}\n"
"")
        self.xmax_i_2.setObjectName("xmax_i_2")
        self.gridLayout_6.addWidget(self.xmax_i_2, 0, 4, 1, 1)
        self.xmin_i_2 = QtWidgets.QLineEdit(self.widget_2)
        self.xmin_i_2.setStyleSheet("QLineEdit {\n"
"    font:7pt \"Verdana\";\n"
"    border: 0.5px solid rgb(196, 196, 196);\n"
"    border-radius: 5px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-color:rgb(146, 209, 244);\n"
"}\n"
"")
        self.xmin_i_2.setObjectName("xmin_i_2")
        self.gridLayout_6.addWidget(self.xmin_i_2, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget_2)
        self.label_19.setStyleSheet("font:7pt \"Verdana\";")
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 1, 0, 1, 1)
        self.ymin_i_2 = QtWidgets.QLineEdit(self.widget_2)
        self.ymin_i_2.setStyleSheet("QLineEdit {\n"
"    font:7pt \"Verdana\";\n"
"    border: 0.5px solid rgb(196, 196, 196);\n"
"    border-radius: 5px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-color:rgb(146, 209, 244);\n"
"}\n"
"")
        self.ymin_i_2.setObjectName("ymin_i_2")
        self.gridLayout_6.addWidget(self.ymin_i_2, 1, 1, 1, 1)
        self.tmax_i_2 = QtWidgets.QLineEdit(self.widget_2)
        self.tmax_i_2.setStyleSheet("QLineEdit {\n"
"    font:7pt \"Verdana\";\n"
"    border: 0.5px solid rgb(196, 196, 196);\n"
"    border-radius: 5px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-color:rgb(146, 209, 244);\n"
"}\n"
"")
        self.tmax_i_2.setObjectName("tmax_i_2")
        self.gridLayout_6.addWidget(self.tmax_i_2, 2, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget_2)
        self.label_16.setStyleSheet("font:7pt \"Verdana\";")
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 2, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget_2)
        self.label_18.setStyleSheet("font:7pt \"Verdana\";")
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget_2)
        self.label_20.setStyleSheet("font:7pt \"Verdana\";")
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 0, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget_2)
        self.label_21.setStyleSheet("font:7pt \"Verdana\";")
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 2, 0, 1, 1)
        self.tmin_i_2 = QtWidgets.QLineEdit(self.widget_2)
        self.tmin_i_2.setStyleSheet("QLineEdit {\n"
"    font:7pt \"Verdana\";\n"
"    border: 0.5px solid rgb(196, 196, 196);\n"
"    border-radius: 5px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-color:rgb(146, 209, 244);\n"
"}\n"
"")
        self.tmin_i_2.setObjectName("tmin_i_2")
        self.gridLayout_6.addWidget(self.tmin_i_2, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget_2)
        self.label_17.setStyleSheet("font:7pt \"Verdana\";")
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 1, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem10, 0, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 3, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setHorizontalSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.saveDir_btn2 = QtWidgets.QPushButton(self.widget_2)
        self.saveDir_btn2.setMinimumSize(QtCore.QSize(0, 21))
        self.saveDir_btn2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 113, 176);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    font:7pt \"Verdana\";\n"
"    border-style:none;\n"
"\n"
"    padding:3px;\n"
"    min-height:15px;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(87, 150, 204);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(46, 101, 156);\n"
"}")
        self.saveDir_btn2.setFlat(False)
        self.saveDir_btn2.setObjectName("saveDir_btn2")
        self.gridLayout_7.addWidget(self.saveDir_btn2, 0, 0, 1, 1)
        self.savedir_line2 = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savedir_line2.sizePolicy().hasHeightForWidth())
        self.savedir_line2.setSizePolicy(sizePolicy)
        self.savedir_line2.setStyleSheet("font:7pt \"Verdana\";\n"
"border: 0.5px solid rgb(196, 196, 196);\n"
"border-radius: 5px")
        self.savedir_line2.setReadOnly(True)
        self.savedir_line2.setObjectName("savedir_line2")
        self.gridLayout_7.addWidget(self.savedir_line2, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.OK_btn_2 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OK_btn_2.sizePolicy().hasHeightForWidth())
        self.OK_btn_2.setSizePolicy(sizePolicy)
        self.OK_btn_2.setMinimumSize(QtCore.QSize(50, 25))
        self.OK_btn_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 113, 176);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    font:7pt \"Verdana\";\n"
"    border-style:none;\n"
"\n"
"    padding:5px;\n"
"    min-height:15px;\n"
"    min-width: 40px;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(87, 150, 204);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(46, 101, 156);\n"
"}")
        self.OK_btn_2.setObjectName("OK_btn_2")
        self.gridLayout_5.addWidget(self.OK_btn_2, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_24 = QtWidgets.QLabel(self.widget_2)
        self.label_24.setStyleSheet("font:7pt \"Verdana\";")
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 2, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.tabWidget.addTab(self.func_tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 2, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.OK_btn.clicked.connect(Form.collect_all_data)
        self.dataF_btn.clicked.connect(Form.dataF_btn_c)
        self.timeF_btn.clicked.connect(Form.timeF_btn_c)
        self.saveDir_btn.clicked.connect(Form.saveDir_btn_c)
        self.OK_btn_2.clicked.connect(Form.collect_all_data2)
        self.saveDir_btn2.clicked.connect(Form.savedir_btn2_c)
        self.function_info.clicked.connect(Form.function_info_c)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabWidget.setWhatsThis(_translate("Form", "<html><head/><body><p>1</p></body></html>"))
        self.dataF_btn.setText(_translate("Form", "Choose the data file"))
        self.timeF_btn.setText(_translate("Form", "Choose the time parameter file"))
        self.saveDir_btn.setText(_translate("Form", "Choose the save directory"))
        self.label_4.setText(_translate("Form", "Choose format of data:"))
        self.data_ver_rbtn.setText(_translate("Form", "vertical"))
        self.data_hor_rbtn.setText(_translate("Form", "horizontal"))
        self.label.setText(_translate("Form", "Title"))
        self.label_2.setText(_translate("Form", "Unit of Time "))
        self.label_3.setText(_translate("Form", "Unit of Axis "))
        self.label_5.setText(_translate("Form", "Select the files you need:"))
        self.save_v_box.setText(_translate("Form", "video"))
        self.save_i_box.setText(_translate("Form", "image"))
        self.OK_btn.setText(_translate("Form", "OK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.data_tab), _translate("Form", "1"))
        self.label_23.setText(_translate("Form", "please make sure the function only has three parameter: x, y, t"))
        self.label_22.setText(_translate("Form", "function"))
        self.function_info.setText(_translate("Form", "?"))
        self.label_15.setText(_translate("Form", "number of frames in the video"))
        self.label_19.setText(_translate("Form", "y min"))
        self.label_16.setText(_translate("Form", "t max"))
        self.label_18.setText(_translate("Form", "x min"))
        self.label_20.setText(_translate("Form", "x max"))
        self.label_21.setText(_translate("Form", "t min"))
        self.label_17.setText(_translate("Form", "y max"))
        self.saveDir_btn2.setText(_translate("Form", " Choose the save directory "))
        self.OK_btn_2.setText(_translate("Form", "OK"))
        self.label_24.setText(_translate("Form", "Set the scale of the plot:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.func_tab), _translate("Form", "2"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
