# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'func_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(362, 324)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/wind_icon.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("QWidget#Dialog {\n"
"    background-color: rgb(202, 219, 255);\n"
"    border-radius: 15px;\n"
"    \n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setMinimumSize(QtCore.QSize(280, 200))
        self.textBrowser.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"border: none;\n"
"    \n"
"font: 7pt \"Verdana\";\n"
"\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.OK_btn_finfo = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OK_btn_finfo.sizePolicy().hasHeightForWidth())
        self.OK_btn_finfo.setSizePolicy(sizePolicy)
        self.OK_btn_finfo.setMinimumSize(QtCore.QSize(50, 25))
        self.OK_btn_finfo.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 113, 176);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    font: 7pt \"Verdana\";\n"
"    border-style:none;\n"
"\n"
"    padding:5px;\n"
"    min-height:15px;\n"
"    min-width: 40px;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(87, 150, 204);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(46, 101, 156);\n"
"}")
        self.OK_btn_finfo.setObjectName("OK_btn_finfo")
        self.verticalLayout.addWidget(self.OK_btn_finfo, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.widget, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.OK_btn_finfo.clicked.connect(Dialog.OK_btn_func_info_c)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Verdana\'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Since the input string of function will be evaluated as Python code directly and the program will handle the input function by NumPy library (I import NumPy as np, which explain the “np.” at the start of every mathematical function in the reference below), please follow the rule of NumPy library. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Here is a simple reference. For more mathematical functions in NumPy, please click <a href=\"https://numpy.org/doc/stable/reference/routines.math.html\"><span style=\" text-decoration: underline; color:#0000ff;\">NumPy - Mathematical functions</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Reference:</span> </p>\n"
"<table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" width=\"248\" cellspacing=\"0\" cellpadding=\"0\">\n"
"<tr>\n"
"<td width=\"144\" style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#000000;\">Input</span> </p></td>\n"
"<td width=\"104\" style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#000000;\">Meaning</span> </p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">+</span> </p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">plus</span> </p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">-</span> </p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">minus</span> </p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">*</span> </p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">multiply</span> </p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">/</span> </p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">divide</span> </p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\"></td>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\"></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">np.exp(x)</span> </p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">e</span><span style=\" color:#000000; vertical-align:super;\">x</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">np.power(x, y)</span> </p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">x</span><span style=\" color:#000000; vertical-align:super;\">y</span></p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\"></td>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\"></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">np.sin(x)</span> </p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">sin(x)</span> </p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">np.arcsin(x)</span> </p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">arcsin(x)</span> </p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">np.sinh(x)</span> </p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">sinh(x)</span> </p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">np.arcsinh(x)</span> </p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#000000;\">arcsinh(x)</span> </p></td></tr>\n"
"<tr>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic; color:#ff0000;\">same as cos, tan</span><span style=\" font-style:italic;\"> </span></p></td>\n"
"<td style=\" vertical-align:bottom; padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\"></td></tr></table>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\"> </span> </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Valid Examples: </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2*np.sin(800*(x+y-5000*t)) + 3*np.cos(1000*(x+2*y-4000*t)) </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">np.cos(np.power(x,3))/2 + np.exp(y)*np.arctanh(t) </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.OK_btn_finfo.setText(_translate("Dialog", "OK"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
