# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progressbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(223, 102)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/wind_icon.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("QWidget#Dialog {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        Dialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.msg = QtWidgets.QLabel(self.widget)
        self.msg.setStyleSheet("font: 7pt \"Verdana\";")
        self.msg.setObjectName("msg")
        self.verticalLayout_2.addWidget(self.msg)
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 1px solid lightgrey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"    font: 7pt \"Verdana\";\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(129, 168, 226);\n"
"    color: white;\n"
"    margin: 0.5px;\n"
"}")
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.widget)
        self.ok_btn = QtWidgets.QPushButton(Dialog)
        self.ok_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok_btn.sizePolicy().hasHeightForWidth())
        self.ok_btn.setSizePolicy(sizePolicy)
        self.ok_btn.setMinimumSize(QtCore.QSize(90, 21))
        self.ok_btn.setStyleSheet("QPushButton:enabled{\n"
"    background-color: rgb(52, 113, 176);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    font: 7pt \"Verdana\";\n"
"    border-style:none;\n"
"\n"
"    padding:3px;\n"
"    min-height:15px;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(87, 150, 204);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(46, 101, 156);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    background-color: lightgray;\n"
"    border-radius: 10px;\n"
"    font: 7pt \"Verdana\";\n"
"    border-style:none;\n"
"\n"
"    padding:3px;\n"
"    min-height:15px;\n"
"    border-radius:5px;\n"
"}")
        self.ok_btn.setObjectName("ok_btn")
        self.verticalLayout.addWidget(self.ok_btn, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(Dialog)
        self.ok_btn.clicked.connect(Dialog.open_folder)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.msg.setText(_translate("Dialog", "Loading...It may take a while"))
        self.ok_btn.setText(_translate("Dialog", "Open the Folder"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
